### ISSUE TITLE
Doesn't chenge the language.

### ISSUE THREAD

**Issue by PrankAlien** [PYRRH4/Potatoes#1]
### Issue description

Doesn't change the language.

### Versions

Spigot : spigot 1.8.8

PyrCore : 3.0.11

Potatoes : 3.2.9

**Comment by PYRRH4** [comment]
Please send me your config file and your language file

**Comment by PrankAlien** [comment]
Thanks i've already resolved.

Il 14 Ott 2017 18:37, "PYRRH4" <notifications@github.com> ha scritto:

**Comment by PrankAlien** [comment]
Great, but you can add the teleport in spectator mode? Also the armor stand
continue to bugs

2017-10-14 18:54 GMT+02:00 Prank Alien <prankalien@gmail.com>:

**Comment by PYRRH4** [comment]
I'm working on it

**Comment by PrankAlien** [comment]
Thanks

Il 17 Ott 2017 11:25, "PYRRH4" <notifications@github.com> ha scritto:

I'm working on it

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PYRRH4/Potatoes/issues/1#issuecomment-337172700>, or mute
the thread

**Comment by PrankAlien** [comment]
Thanks

Il 17 Ott 2017 12:09, prankalien@gmail.com ha scritto:

Thanks

Il 17 Ott 2017 11:25, "PYRRH4" <notifications@github.com> ha scritto:

I'm working on it

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PYRRH4/Potatoes/issues/1#issuecomment-337172700>, or mute
the thread
