### ISSUE TITLE
Games are not starting at all

### ISSUE THREAD

**Issue by LadyHaley** [PYRRH4/Potatoes#2]
### Issue description
I installed the plugin and went to start a game after setting up an arena but it won't work and I'm unsure why
It spat this out but idk what it means https://pastebin.com/U7SPrczH

### Versions

Spigot : CraftBukkit version git-Spigot-5695bca-53fccdf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

PyrCore : 3.1.5

Potatoes : 3.2.13

### Log file
I cant add the log file, chrome crashes when i try uploading it to pastebin but i can upload it elsewhere if you need it

**Comment by PYRRH4** [comment]
Are you sure you have the scoreboard_ messages with all the phases in the locale file ?

**Comment by PYRRH4** [comment]
Really ? Any errors on start somehow ?

**Comment by LadyHaley** [comment]
I am unable to find any errors on startup for the plugin

**Comment by PYRRH4** [comment]
Does the error persist still today ?
