### ISSUE TITLE
Teleport lobby player, finish and death.

### ISSUE THREAD

**Issue by infinity3113** [PYRRH4/Potatoes#3]
### Issue description
Any way that when the game ends the players of that game return to the lobby?

### Versions

Spigot : 1.11.2

PyrCore : 3.2.0

Potatoes : 3.2.14

**Comment by infinity3113** [comment]
The problem of returning to the lobby was my mistake, I forgot to put an option to the arena.

But there is a problem, when I set to give objects when the game ends it does not work, I mean as in the default configuration (Give $PlAYER Diamond 1) It shows the message in the console that gave the diamond, but in the player's inventory it does not there is nothing.

**Comment by PYRRH4** [comment]
Fixing it for the next version ^^

**Comment by PYRRH4** [comment]
Fixed in [Potatoes v3.2.15](https://www.spigotmc.org/resources/12353/update?update=204253)
