### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by PrankAlien** [PYRRH4/Potatoes#4]
### Issue description
Keep Exploding and the timer delete 2 seconds.

### Versions

Spigot : 1.8.8

PyrCore : 3.2.1

Potatoes : 3.2.15

### Log file

[latest.log](https://github.com/PYRRH4/Potatoes/files/1594451/latest.log)

**Comment by PYRRH4** [comment]
Shoud be fixed in [Potatoes v3.2.16](https://www.spigotmc.org/resources/12353/update?update=204328)
